#! /bin/bash
rustup target add i686-linux-android && 
rustup target add aarch64-linux-android &&
rustup target add armv7-linux-androideabi &&

#export PATH=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/:$PATH
#export CC_aarch64_linux_android=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang
#export CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang

#Android
cd swapi_adr/scripts
./release_build &&
./create_s_link

cd -

#IOS
cd swapi_ios/scripts
./release_build
